package cli_test

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// compactAuditSpec carries enough structured elements (list items and table
// rows across three sections) that the routed checklist is worth measuring.
const compactAuditSpec = `# Widget Service

## 1. Storage
- The store persists every widget with an id, a name and a created_at timestamp.
- A widget id is a ULID and is generated by the store, never by the caller.
- Writing a widget that already exists replaces it and bumps updated_at.

| Field | Type | Required |
|-------|------|----------|
| id | string | yes |
| name | string | yes |
| created_at | time | yes |

## 2. API
- POST /widgets creates a widget and returns 201 with the created body.
- GET /widgets lists every widget ordered by created_at descending.
- GET /widgets/{id} returns 404 when the id is unknown.
- DELETE /widgets/{id} is idempotent and always returns 204.

| Endpoint | Method | Status |
|----------|--------|--------|
| /widgets | POST | 201 |
| /widgets | GET | 200 |
| /widgets/{id} | DELETE | 204 |

## 3. Validation
- A name shorter than 2 characters is rejected with 422.
- A name longer than 64 characters is rejected with 422.
- Unknown JSON fields in the request body are rejected with 400.
`

// setupCompactAuditProject lays out the fixture the compact measurement needs:
// three auditor roles (spec-coverage plus two that take the shared file_check
// arm) over five source files, so both duplicated per-prompt fields are large
// enough for the ratio to mean something.
func setupCompactAuditProject(t *testing.T) (dir string, files []string) {
	t.Helper()
	dir = t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(dir, ".git"), 0o755))
	audDir := filepath.Join(dir, ".tp", "auditors")
	require.NoError(t, os.MkdirAll(audDir, 0o755))
	for _, id := range []string{"spec-coverage", "go-safety", "ax-contract"} {
		require.NoError(t, os.WriteFile(filepath.Join(audDir, id+".json"),
			[]byte(`{"id":"`+id+`","title":"`+id+`","instructions":"You audit."}`), 0o600))
	}
	require.NoError(t, os.WriteFile(filepath.Join(dir, "spec.md"), []byte(compactAuditSpec), 0o600))

	for _, name := range []string{"store", "api", "validate", "handler", "middleware"} {
		rel := name + ".go"
		body := fmt.Sprintf("package src\n\n// %s holds the %s logic.\nfunc %s() string {\n\treturn %q\n}\n", name, name, name, name)
		require.NoError(t, os.WriteFile(filepath.Join(dir, rel), []byte(body), 0o600))
		files = append(files, rel)
	}
	return dir, files
}

// auditArgs builds "audit spec.md [--compact] --affected-files f ..." — the
// files are passed explicitly so the measurement does not depend on git.
func auditArgs(files []string, compact bool) []string {
	args := []string{"audit", "spec.md"}
	if compact {
		args = append(args, "--compact")
	}
	for _, f := range files {
		args = append(args, "--affected-files", f)
	}
	return args
}

// TestAuditCompact_DropsDuplicatedPerPromptFields: --compact promises roughly a
// 40% smaller payload, and on the audit payload it was delivering 0.5% — it
// truncated checklist[].text and dropped file_summary, and left the two largest
// compressible fields alone. prompts[].checklist_items and
// prompts[].affected_files are a verbatim duplicate of what buildRolePrompt
// already rendered into prompts[].prompt, so the spec items shipped three times
// over: once in the top-level checklist, once per prompt as structured JSON, and
// once again inside the prompt body an agent actually reads.
//
// The two discriminating halves: the compact payload is materially smaller
// (asserted as a ratio, so it cannot be satisfied by trimming a few bytes), and
// nothing an agent needs was lost — every dropped item id and file path is still
// inside prompts[].prompt.
func TestAuditCompact_DropsDuplicatedPerPromptFields(t *testing.T) {
	dir, files := setupCompactAuditProject(t)

	full, stderr, code := runTP(t, dir, auditArgs(files, false)...)
	require.Equal(t, 0, code, "stderr: %s", stderr)
	compact, stderr, code := runTP(t, dir, auditArgs(files, true)...)
	require.Equal(t, 0, code, "stderr: %s", stderr)

	assert.Less(t, len(compact)*100, len(full)*85,
		"--compact must be materially smaller: full=%d compact=%d", len(full), len(compact))

	fullPrompts := auditPromptsByRole(t, full)
	compactPrompts := auditPromptsByRole(t, compact)
	require.Len(t, fullPrompts, 3, "the fixture must emit all three auditor roles")
	require.Equal(t, len(fullPrompts), len(compactPrompts), "--compact drops no prompt")

	for role, p := range fullPrompts {
		require.Contains(t, p, "checklist_items", "default output keeps checklist_items (role %s)", role)
		require.Contains(t, p, "affected_files", "default output keeps affected_files (role %s)", role)
		require.NotEmpty(t, p["checklist_items"], "role %s must have routed items", role)

		cp := compactPrompts[role]
		require.NotNil(t, cp, "role %s survives --compact", role)
		assert.NotContains(t, cp, "checklist_items", "--compact omits the duplicated checklist_items (role %s)", role)
		assert.NotContains(t, cp, "affected_files", "--compact omits the duplicated affected_files (role %s)", role)

		// Nothing was lost: the prompt body still carries every dropped id.
		body, _ := cp["prompt"].(string)
		require.NotEmpty(t, body, "role %s keeps its prompt", role)
		for _, raw := range p["checklist_items"].([]any) {
			itemID := raw.(map[string]any)["item_id"].(string)
			assert.Contains(t, body, itemID,
				"role %s: item %s must still be readable inside prompts[].prompt", role, itemID)
		}
		for _, raw := range p["affected_files"].([]any) {
			path := raw.(map[string]any)["path"].(string)
			assert.Contains(t, body, path,
				"role %s: file %s must still be readable inside prompts[].prompt", role, path)
		}
	}
}

// TestAuditCompact_DefaultOutputUnchanged pins the other side of the switch: the
// saving is opt-in. A caller that did not ask for --compact still receives both
// fields, spelled as arrays rather than omitted or null.
func TestAuditCompact_DefaultOutputUnchanged(t *testing.T) {
	dir, files := setupCompactAuditProject(t)

	full, stderr, code := runTP(t, dir, auditArgs(files, false)...)
	require.Equal(t, 0, code, "stderr: %s", stderr)

	var out map[string]any
	require.NoError(t, json.Unmarshal([]byte(full), &out))
	for _, raw := range out["prompts"].([]any) {
		p := raw.(map[string]any)
		role := p["role"].(string)
		items, ok := p["checklist_items"].([]any)
		require.True(t, ok, "role %s: checklist_items is an array, never null", role)
		assert.NotEmpty(t, items)
		fileEntries, ok := p["affected_files"].([]any)
		require.True(t, ok, "role %s: affected_files is an array, never null", role)
		assert.NotEmpty(t, fileEntries)
	}
	assert.False(t, strings.Contains(full, `"checklist_items":null`), "a nil slice must not reach the payload")
	assert.False(t, strings.Contains(full, `"affected_files":null`), "a nil slice must not reach the payload")
}
